targets:
  $default:
    sources:
      - lib/**
      - resources/swagger/**
      - $package$
    builders:
      swagger_dart_code_generator:
        options:
          input_folder: 'resources/swagger'
          output_folder: 'lib/api'